import{test}from'node:test';import assert from'node:assert/strict';import{load}from'../scripts/load-content.mjs';import fs from'node:fs';import{regionsFor,locationPending}from'../src/relationships.mjs';import{validateCatalog,validateRoute,restoreDraft,youtube,safeUrl,changedFiles,routeEdges,routeColumns,selectedRoutePath}from'../src/validation.mjs';const c=load();
test('complete imported catalog validates',()=>assert.deepEqual(validateCatalog(c),[]));
test('historical source snapshot retains required cases',()=>{const s=JSON.parse(fs.readFileSync('content/source-snapshot.json')),e=id=>s.entries.values.find(e=>e[0]===id);assert.equal(e('MCD2-001')[7],4);assert.match(e('MCD2-001')[5],/Sézchavèire/);assert.equal(e('MCD2-032')[7],0);assert.equal(e('MCD2-005')[7],0);assert.match(e('MCD2-028')[6],/touch the space behind the door/);assert.match(e('MCD2-026')[6],/no separate blue-door jump/);assert.equal(e('MCD2-002')[7],3);assert.match(e('MCD2-002')[6],/Red Tower/);assert.match(s.videos.values.find(v=>v[0]==='VID-024')[4],/1515423123342627048/);assert.deepEqual(s.videos.values.filter(v=>v[1]==='MCD2-035').map(v=>v[0]),['VID-045','VID-046']);});
test('unsafe links and YouTube forms',()=>{assert.equal(safeUrl('javascript:alert(1)'),false);assert.equal(safeUrl('https://a:b@example.com/'),false);assert.deepEqual(youtube('https://youtu.be/AUgQXbDqRDA?t=1m20s'),{id:'AUgQXbDqRDA',start:80});assert.equal(youtube('https://youtube.com.evil.com/watch?v=AUgQXbDqRDA'),null);assert.equal(youtube('https://www.youtube.com/shorts/AUgQXbDqRDA')?.id,'AUgQXbDqRDA');});
const stage=(id,next='',result=[])=>({id,title:id,type:'Travel',regionId:'',subsectionId:'',action:'',rationale:'',warnings:'',requires:[],result,entryId:'',methodId:'',mediaIds:[],next,choices:[]});const branch=(id,result,next='end')=>({id,title:id,rationale:'',requires:[],result,next,actions:[{id:id+'-action',title:'Action',entryId:'',methodId:'',requires:[],result:[],warnings:'',mediaIds:[]}],timing:'',reliability:'',basisDate:''});const route=()=>({id:'test',title:'Fixture',status:'sample',sample:true,dependencyReviewed:false,gameplayTested:false,stages:[{...stage('start'),choices:[branch('a',['done']),branch('b',['done'])]},stage('end')]});
test('parallel alternatives, multiple actions and compatible merge validate',()=>{const r=route();r.stages[0].choices[1].actions.push({...r.stages[0].choices[1].actions[0],id:'second-action'});assert.deepEqual(validateRoute(r,c),[]);});
test('incompatible declared quest states block merge',()=>{const r=route();r.stages[0].choices[1].result=['other'];assert.ok(validateRoute(r,c).some(e=>e.includes('Incompatible reconvergence')));});
test('cycles, unreachable visits and missing references are detected',()=>{const r=route();r.stages[1].next='start';assert.ok(validateRoute(r,c).some(e=>e.includes('cycle')));const x=route();x.stages.push(stage('orphan'));x.stages[1].next='end';assert.ok(validateRoute(x,c).some(e=>e.includes('Unreachable')));const y=route();y.stages[0].entryId='MCD2-999';assert.ok(validateRoute(y,c).some(e=>e.includes('Unknown entry')));});
test('stage reorder retains identities and branch data',()=>{const r=route(),id=r.stages[0].id,actions=structuredClone(r.stages[0].choices);r.stages.reverse();assert.equal(r.stages[1].id,id);assert.deepEqual(r.stages[1].choices,actions);});
test('draft round trip and stale/schema conflicts',()=>{const d={schemaVersion:1,baseRevision:c.meta.revision,catalog:c,assets:[]};assert.deepEqual(restoreDraft(JSON.parse(JSON.stringify(d)),c.meta.revision),d);assert.throws(()=>restoreDraft(d,'newer'),/Revision conflict/);assert.throws(()=>restoreDraft({...d,schemaVersion:99},c.meta.revision),/Unsupported/);});
test('changed paths isolate edits',()=>{const edited=structuredClone(c);edited.entries[0].summary='New description';assert.deepEqual(changedFiles(c,edited),['content/entries/MCD2-001.json']);});
test('unknown locations remain unassigned',()=>{for(const id of ['MCD2-008','MCD2-018','MCD2-034'])assert.deepEqual(c.entries.find(e=>e.id===id).regionIds,[]);});

test('later graph joins compare all paths and dependencies',()=>{const r=route();r.stages=[{...stage('A'),choices:[branch('left',[],'B'),branch('right',[],'C')]},stage('B','D',['gold-key']),stage('C','D'),{...stage('D'),requires:['gold-key']}];const errors=validateRoute(r,c);assert.ok(errors.some(e=>e.includes('Incompatible reconvergence at D')));assert.ok(errors.some(e=>e.includes('Unmet declared dependency at D')));});
test('malformed nested content is rejected without throwing',()=>{const bad=structuredClone(c);bad.entries[0].credits.discovery={bad:'object'};assert.ok(validateCatalog(bad).length);const r=route();r.stages=[null];assert.ok(validateRoute(r,c).length);assert.ok(validateCatalog({...c,entries:[]}).length);});

test('graph layout and reading paths honor divergent next stages',()=>{const r=route();r.stages=[{...stage('A'),choices:[branch('left',[],'B'),branch('right',[],'C')]},stage('B','D'),stage('C','D'),stage('D')];assert.deepEqual(routeColumns(r).map(col=>col.map(s=>s.id)),[['A'],['B','C'],['D']]);assert.deepEqual(selectedRoutePath(r,{A:'right'}),['A','C','D']);assert.deepEqual(selectedRoutePath(r,{}),['A']);assert.equal(routeEdges(r).find(e=>e.sourceId==='right').target,'C');assert.deepEqual(validateRoute(r,c),[]);});
test('confirmed subsection exposes its single associated entry in region',()=>{const x=structuredClone(c),e=x.entries.find(e=>e.id==='MCD2-018'),s=x.subsections.find(s=>s.id===e.subsectionIds[0]);s.regionId='honeycomb-fields';assert.ok(regionsFor(e,x).includes('honeycomb-fields'));assert.equal(locationPending(e,x),false);assert.equal(x.entries.filter(e=>e.id==='MCD2-018').length,1);});
test('editorial updates and added tutorial validate without immutable import parity',()=>{const x=structuredClone(c);x.entries[0].notes+='\nAuthor correction.';const v={...x.videos[0],id:'VID-047',role:'Tutorial',sourceType:'YouTube',url:'https://youtu.be/AUgQXbDqRDA'};x.videos.push(v);x.entries[0].mediaIds.push(v.id);x.entries[0].methods[0].mediaIds.push(v.id);assert.deepEqual(validateCatalog(x),[]);});
test('screenshot draft binary and metadata round trip, duplicate paths rejected',()=>{const x=structuredClone(c),path='public/images/subsections/test.png';x.subsections[0].image={path,alt:'A supplied screenshot',credit:'Contributor',focalX:.3,focalY:.7};const d={schemaVersion:1,baseRevision:x.meta.revision,catalog:x,assets:[{path,data:'data:image/png;base64,iVBORw0KGgo='}]};assert.deepEqual(restoreDraft(JSON.parse(JSON.stringify(d)),x.meta.revision),d);assert.throws(()=>restoreDraft({...d,assets:[...d.assets,...d.assets]},x.meta.revision),/duplicate/);});
test('unfinished safe tutorial drafts can restore while publication remains blocked',()=>{const x=structuredClone(c);x.videos[0].url='';const d={schemaVersion:1,baseRevision:c.meta.revision,catalog:x,assets:[]};assert.throws(()=>restoreDraft(d,c.meta.revision,c),/Invalid/);assert.deepEqual(restoreDraft(d,c.meta.revision,c,{allowIncomplete:true}),d);x.videos[0].url='javascript:alert(1)';assert.throws(()=>restoreDraft(d,c.meta.revision,c,{allowIncomplete:true}),/Invalid/);});
test('unknown screenshot asset is rejected on restoration',()=>{const x=structuredClone(c);x.subsections[0].image={path:'public/images/subsections/missing.png',alt:'Missing bytes',credit:'',focalX:.5,focalY:.5};assert.throws(()=>restoreDraft({schemaVersion:1,baseRevision:c.meta.revision,catalog:x,assets:[]},c.meta.revision,c),/Missing screenshot bytes/);});

test('divergent terminal visits end independently without false reconvergence',()=>{const r=route();r.stages=[{...stage('A'),choices:[branch('left',[],'B'),branch('right',[],'C')]},stage('B','__end__',['left-result']),stage('C','__end__',['right-result'])];assert.deepEqual(validateRoute(r,c),[]);assert.deepEqual(selectedRoutePath(r,{A:'left'}),['A','B']);assert.deepEqual(selectedRoutePath(r,{A:'right'}),['A','C']);assert.equal(routeEdges(r).length,2);});
test('draft assets cannot overwrite immutable published screenshot paths',()=>{const published=structuredClone(c);published.subsections[0].image={path:'public/images/subsections/published.png',alt:'Published',credit:'Author',focalX:.5,focalY:.5};const d={schemaVersion:1,baseRevision:c.meta.revision,catalog:published,assets:[{path:'public/images/subsections/published.png',data:'data:image/png;base64,AAAA'}]};assert.throws(()=>restoreDraft(d,c.meta.revision,published),/immutable/);});
test('search indexes places, separate credits, methods and prerequisites',async()=>{const {matchesSearch}=await import('../src/search.mjs');const x=structuredClone(c);x.entries[0].credits.narration='Unique narrator';x.entries[0].methods[0].requirements.equipment=['Test boots'];assert.ok(matchesSearch(x.entries[0],x,'unique narrator'));assert.ok(matchesSearch(x.entries[0],x,'test boots'));assert.equal(matchesSearch(x.entries[0],x,'mediaIds'),false);assert.ok(matchesSearch(x.entries.find(e=>e.id==='MCD2-015'),x,'honeycomb fields'));});
