import React,{useState,useEffect,useRef,useLayoutEffect} from 'react';import type{Catalog,Route,Stage,Choice,Action}from'./types';import{validateRoute,routeEdges,routeColumns,selectedRoutePath,routeDestination}from'./validation.mjs';
const blankAction=(id:string,title:string):Action=>({id,title,entryId:'',methodId:'',requires:[],result:[],warnings:'',mediaIds:[]});
export const sampleRoute:Route={id:'sample',title:'Branching viewer example',status:'Sample fixture · not an actual Any% route',sample:true,dependencyReviewed:false,gameplayTested:false,stages:[{id:'sample-setup',title:'Illustrative setup',type:'Setup',regionId:'',subsectionId:'',action:'A sample starting checkpoint. No game route is asserted.',rationale:'Shows the start of a sequence with a unique visit ID.',warnings:'Example content only.',requires:[],result:['example-ready'],entryId:'',methodId:'',mediaIds:[],next:'sample-options',choices:[]},{id:'sample-options',title:'Choose one approach',type:'Travel',regionId:'',subsectionId:'',action:'Three mutually exclusive options share this stage.',rationale:'Choose one approach; the three alternatives are not three required steps.',warnings:'No timings or gameplay reliability are asserted.',requires:['example-ready'],result:[],entryId:'',methodId:'',mediaIds:[],next:'sample-objective',choices:[{id:'sample-normal',title:'Normal route example',rationale:'Demonstrates a walk/combat alternative alongside technique options.',requires:[],result:['example-checkpoint'],next:'sample-objective',actions:[blankAction('sample-walk','Follow the supplied normal path')],timing:'',reliability:'',basisDate:''},{id:'sample-tech',title:'Technique option example',rationale:'Demonstrates a stable link to foundational tech, without claiming it fits an actual route.',requires:[],result:['example-checkpoint'],next:'sample-objective',actions:[{...blankAction('sample-use','Read the linked technique'),'entryId':'MCD2-001','methodId':'MCD2-001-method-1'}],timing:'',reliability:'',basisDate:''},{id:'sample-multi',title:'Multiple actions example',rationale:'Both actions belong to this one alternative.',requires:[],result:['example-checkpoint'],next:'sample-objective',actions:[blankAction('sample-align','Prepare the position'),blankAction('sample-move','Complete the approach')],timing:'',reliability:'',basisDate:''}]},{id:'sample-objective',title:'Required objective check',type:'Objective',regionId:'',subsectionId:'',action:'All sample alternatives arrive with the same declared checkpoint state.',rationale:'Illustrates safe reconvergence after equivalent result states.',warnings:'Real quest checkpoints must come from approved route content.',requires:['example-checkpoint'],result:[],entryId:'',methodId:'',mediaIds:[],next:'',choices:[]}]};
export function RouteReader({catalog,routeOverride}:{catalog:Catalog;routeOverride?:Route}){
 const params=new URLSearchParams(location.hash.split('?')[1]),guide=params.get('guide')||catalog.routes[0]?.id;
 const route=routeOverride||(guide==='sample'?catalog.routes.find(r=>r.id==='sample')||sampleRoute:catalog.routes.find(r=>r.id===guide)||catalog.routes[0]);
 const [view,setView]=useState<'chart'|'reading'>(matchMedia('(max-width:760px)').matches?'reading':'chart');
 const [selected,setSelected]=useState(params.get('stage')||route.stages[0]?.id||'');
 const [choices,setChoices]=useState<Record<string,string>>({});
 const container=useRef<HTMLDivElement>(null),track=useRef<HTMLDivElement>(null);
 const [connections,setConnections]=useState<{width:number;height:number;paths:string[]}>({width:0,height:0,paths:[]});
 const [fullError,setFullError]=useState('');
 useEffect(()=>{if(routeOverride){setSelected(route.stages[0]?.id||'');return;}const p=new URLSearchParams(location.hash.split('?')[1]);setSelected(p.get('stage')||route.stages[0]?.id||'');const branches:Record<string,string>={};p.forEach((v,k)=>{if(k.startsWith('branch-'))branches[k.slice(7)]=v;});setChoices(branches);},[route.id,location.hash]);
 const edges=routeEdges(route),columns=routeColumns(route) as Stage[][],path=selectedRoutePath(route,choices) as string[];
 const s=route.stages.find(s=>s.id===selected)||route.stages[0],errors=validateRoute(route,catalog);
 useLayoutEffect(()=>{if(view!=='chart'||!track.current)return;const el=track.current;const update=()=>{const box=el.getBoundingClientRect();const paths:string[]=[];for(const edge of edges){const a=el.querySelector<HTMLElement>(`[data-output="${edge.sourceId}"]`),b=el.querySelector<HTMLElement>(`[data-input="${edge.target}"]`);if(!a||!b)continue;const ab=a.getBoundingClientRect(),bb=b.getBoundingClientRect(),x1=ab.right-box.left,y1=ab.top+ab.height/2-box.top,x2=bb.left-box.left,y2=bb.top+bb.height/2-box.top,middle=x1+(x2-x1)/2;paths.push(`M ${x1} ${y1} H ${middle} V ${y2} H ${x2}`);}const next={width:el.scrollWidth,height:el.scrollHeight,paths};setConnections(old=>JSON.stringify(old)===JSON.stringify(next)?old:next);};update();const observer=new ResizeObserver(update);observer.observe(el);window.addEventListener('resize',update);document.fonts.ready.then(update);return()=>{observer.disconnect();window.removeEventListener('resize',update);};},[route,view,JSON.stringify(choices)]);
 const select=(id:string)=>{setSelected(id);if(view==='reading'&&!path.includes(id))setView('chart');if(!routeOverride){const p=new URLSearchParams(location.hash.split('?')[1]);p.set('guide',route.id);p.set('stage',id);location.hash='/guides?'+p.toString();}};
 const choose=(stage:string,choice:string)=>{setChoices({...choices,[stage]:choice});setSelected(stage);if(!routeOverride){const p=new URLSearchParams(location.hash.split('?')[1]);p.set('guide',route.id);p.set('stage',stage);p.set('branch-'+stage,choice);location.hash='/guides?'+p.toString();}};
 const entryLink=(entry:string,method:string)=>{const e=catalog.entries.find(e=>e.id===entry);return e?<a href={'#/entry/'+entry+'?method='+encodeURIComponent(method)+'&from='+encodeURIComponent(location.hash.slice(2))}>{e.title}{method&&' · '+(e.methods.find(m=>m.id===method)?.title||method)}</a>:null;};
 const media=(ids:string[])=>ids.map(id=>{const v=catalog.videos.find(x=>x.id===id);return v?<p key={id}><a href={v.url} target="_blank" rel="noreferrer">{v.title} · {v.role}</a></p>:null;});
 const stageCard=(st:Stage)=>{
  const i=route.stages.indexOf(st),out=st.choices.length?{}:{'data-output':st.id};
  return <section className="route-stage" key={st.id} data-stage={st.id}>
   <button {...out} data-input={st.id} className="stage-card" aria-pressed={selected===st.id} aria-describedby={'rationale-'+route.id+'-'+st.id} onFocus={()=>setSelected(st.id)} onClick={()=>select(st.id)}>
    <small>VISIT {String(i+1).padStart(2,'0')} · {st.type}</small><h3>{st.title}</h3><small>{catalog.regions.find(r=>r.id===st.regionId)?.name||'Region to confirm'}{st.subsectionId&&' · '+catalog.subsections.find(x=>x.id===st.subsectionId)?.name}</small><p>{st.action}</p>
   </button>
   <p className="rationale-preview" id={'rationale-'+route.id+'-'+st.id}>Why: {st.rationale||'Rationale not supplied'}</p>
   {st.requires.length>0&&<p className="help">Requires: {st.requires.join(', ')}</p>}
   {st.entryId&&<p>{entryLink(st.entryId,st.methodId)}</p>}{st.warnings&&<p className="help">Caution: {st.warnings}</p>}
   {st.choices.length>0&&<div className="alternatives" aria-label="Choose one alternative">{st.choices.map(ch=><div data-output={ch.id} key={ch.id} className={'alternative'+(choices[st.id]===ch.id?' selected':'')}>
    <h4>{ch.title}</h4><button className="compact" title={ch.rationale} aria-pressed={choices[st.id]===ch.id} onClick={()=>choose(st.id,ch.id)}>{choices[st.id]===ch.id?'Chosen alternative':'Choose this alternative'}</button>
    <p>{ch.rationale||'Rationale not supplied'}</p>{ch.requires.length>0&&<p>Requires: {ch.requires.join(', ')}</p>}
    <ol>{ch.actions.map(a=><li key={a.id}>{a.title}{a.entryId&&<div>{entryLink(a.entryId,a.methodId)}</div>}{a.requires.length>0&&<p>Conditions: {a.requires.join(', ')}</p>}{a.warnings&&<p>Caution: {a.warnings}</p>}</li>)}</ol>
    <small>Next: {route.stages.find(x=>x.id===routeDestination(route,i,ch))?.title||'Guide ends'}</small>
   </div>)}</div>}
   {view==='reading'&&<label style={{marginTop:'1rem'}}><span><input type="checkbox" style={{width:'auto',marginRight:'.5rem'}}/> Mark this visit complete · this session</span></label>}
  </section>;
 };
 return <section>
  <div className="page-heading"><div><p className="eyebrow">SPEEDRUN GUIDES</p><h1>{route.title}</h1><p className="muted">{route.status}</p></div><div className="toolbar">{!routeOverride&&<><label>Guide<select value={route.id} onChange={e=>{location.hash='/guides?guide='+encodeURIComponent(e.target.value);}}>{catalog.routes.map(r=><option value={r.id} key={r.id}>{r.title}</option>)}{!catalog.routes.some(r=>r.id==='sample')&&<option value="sample">Branching viewer example</option>}</select></label><a href="#/guides?guide=sample">View branching example</a></>}</div></div>
  {route.sample&&<div className="notice">Sample fixture only. This sequence does not describe the current Any% route.</div>}
  <div className="card-tags"><span className="chip">{errors.length?'Validation errors':'Schema valid'}</span><span className="chip">Dependencies {route.dependencyReviewed?'reviewed':'not reviewed'}</span><span className="chip">Gameplay {route.gameplayTested?'tested':'not tested'}</span></div>
  {errors.length>0&&<div className="notice">{errors.join('\n')}</div>}
  {!route.stages.length?<div className="empty-state"><span className="frame-mark">◈</span><h2>Actual route awaiting approved steps</h2><p>Order, objective checkpoints, alternatives and rationale have not been supplied.</p><div className="toolbar" style={{justifyContent:'center'}}><a href="#/studio?tab=routes">Open Route Builder</a><a href="#/guides?guide=sample">Explore the labeled example</a></div></div>:<>
   <div className="toolbar"><button aria-pressed={view==='chart'} onClick={()=>setView('chart')}>Horizontal chart</button><button aria-pressed={view==='reading'} onClick={()=>setView('reading')}>Reading / checklist</button><button onClick={()=>container.current?.querySelector(`[data-stage="${s?.id}"]`)?.scrollIntoView({block:'nearest',inline:'center',behavior:'auto'})}>Fit current stage</button><button onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else container.current?.requestFullscreen().catch(()=>setFullError('Fullscreen is unavailable. Both route views remain usable.'));}}>Fullscreen</button></div>
   {fullError&&<p className="help">{fullError}</p>}
   <nav className="stage-nav" aria-label="Route stages">{route.stages.map((st,i)=><button key={st.id} aria-pressed={selected===st.id} onClick={()=>select(st.id)}>{i+1}. {st.title}</button>)}</nav>
   {view==='reading'&&<p className="help">This checklist follows your chosen alternatives. Choose one option at each branch to continue. The chart shows every authored visit and alternative.</p>}
   <div ref={container} className={view==='chart'?'route-scroll':'route-reading'} style={{marginTop:'1rem'}}>
    {view==='chart'?<div ref={track} className="route-track"><svg className="connectors" width={connections.width} height={connections.height} aria-hidden="true"><defs><marker id={'arrow-'+route.id} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#718ea3"/></marker></defs>{connections.paths.map((d,i)=><path key={i} d={d} stroke="#718ea3" strokeWidth="2" fill="none" markerEnd={`url(#arrow-${route.id})`}/>)}</svg>{columns.map((col,i)=><div className="route-column" key={i}>{col.map(stageCard)}</div>)}</div>:<div className="route-reading">{path.map(id=>route.stages.find(s=>s.id===id)).filter(Boolean).map(st=>stageCard(st!))}</div>}
   </div>
   {s&&<section className="panel route-details" aria-live="polite"><div className="route-heading"><h2>{s.title} · Why this step?</h2><small>{s.id}</small></div><p>{s.rationale||'Rationale awaiting author input.'}</p>{s.requires.length>0&&<p>Declared conditions: {s.requires.join(', ')}</p>}{s.result.length>0&&<p>Result / objective state: {s.result.join(', ')}</p>}{s.warnings&&<p className="caution">{s.warnings}</p>}{media(s.mediaIds)}{s.choices.find(ch=>ch.id===choices[s.id])&&<><h3>Selected alternative</h3><p>{s.choices.find(ch=>ch.id===choices[s.id])?.rationale}</p>{s.choices.find(ch=>ch.id===choices[s.id])?.timing&&<p>Timing observation: {s.choices.find(ch=>ch.id===choices[s.id])?.timing}</p>}{s.choices.find(ch=>ch.id===choices[s.id])?.reliability&&<p>Reliability observation: {s.choices.find(ch=>ch.id===choices[s.id])?.reliability}</p>}{s.choices.find(ch=>ch.id===choices[s.id])?.basisDate&&<p>Basis / date: {s.choices.find(ch=>ch.id===choices[s.id])?.basisDate}</p>}{s.choices.find(ch=>ch.id===choices[s.id])?.actions.map(a=><div key={a.id}><strong>{a.title}</strong>{a.requires.length>0&&<p>Conditions: {a.requires.join(', ')}</p>}{a.result.length>0&&<p>Result: {a.result.join(', ')}</p>}{media(a.mediaIds)}</div>)}</>}</section>}
  </>}
 </section>;
}
