const str=x=>typeof x==='string';
const strings=x=>Array.isArray(x)&&x.every(str);
const obj=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const req=x=>obj(x)&&['all','any'].includes(x.mode)&&['entryIds','equipment','quests'].every(k=>strings(x[k]));
const idOrEmpty=x=>str(x)&&(x===''||/^[-\w]+$/.test(x));const ref=x=>obj(x)&&idOrEmpty(x.entryId)&&idOrEmpty(x.methodId)&&strings(x.mediaIds)&&x.mediaIds.every(idOrEmpty);
const hasStrings=(x,keys)=>obj(x)&&keys.every(k=>str(x[k]));
const factFields=x=>obj(x)&&strings(x.requires)&&strings(x.result);
function actionShape(x){return ref(x)&&factFields(x)&&hasStrings(x,['id','title','warnings']);}
function choiceShape(x){return factFields(x)&&hasStrings(x,['id','title','rationale','next','timing','reliability','basisDate'])&&idOrEmpty(x.next)&&Array.isArray(x.actions)&&x.actions.length>0&&x.actions.every(actionShape);}
function stageShape(x){return ref(x)&&factFields(x)&&hasStrings(x,['id','title','type','regionId','subsectionId','action','rationale','warnings','next'])&&idOrEmpty(x.next)&&Array.isArray(x.choices)&&x.choices.every(choiceShape);}
function routeShape(x){return hasStrings(x,['id','title','status'])&&typeof x.sample==='boolean'&&typeof x.dependencyReviewed==='boolean'&&typeof x.gameplayTested==='boolean'&&Array.isArray(x.stages)&&x.stages.every(stageShape);}
export function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
export function youtube(value){try{const u=new URL(value);if(!safeUrl(value))return null;let id=null;if(['youtu.be','www.youtu.be'].includes(u.hostname))id=u.pathname.slice(1).split('/')[0];else if(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([^/]+)/)?.[1];if(!id||!/^[-\w]{11}$/.test(id))return null;const t=u.searchParams.get('t')||u.searchParams.get('start')||'0';const match=t.match(/^(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$/);const start=/^\d+$/.test(t)?Number(t):match?Number(match[1]||0)*3600+Number(match[2]||0)*60+Number(match[3]||0):0;return{id,start:Math.min(start,2147483647)};}catch{return null;}}
export function assetPath(p){return str(p)&&/^public\/images\/subsections\/[a-zA-Z0-9_-]+\.(png|jpe?g|webp)$/.test(p);}
export function contentFiles(c){const files={'content/meta.json':c.meta,'content/regions.json':c.regions,'content/subsections.json':c.subsections,'content/videos.json':c.videos};for(const e of c.entries)files['content/entries/'+e.id+'.json']=e;for(const r of c.routes)files['content/routes/'+r.id+'.json']=r;return files;}
export function changedFiles(before,after){const a=contentFiles(before),b=contentFiles(after);return [...new Set([...Object.keys(a),...Object.keys(b)])].filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k])).sort();}
// Reserved destination: an explicit terminal visit, independent of display order.
export const ROUTE_END='__end__';
/** @param {any} route @param {number} index @param {{next:string}|null} choice */
export function routeDestination(route,index,choice=null){const stage=route.stages[index];const next=choice?.next||stage.next||route.stages[index+1]?.id||'';return next===ROUTE_END?'':next;}
export function routeEdges(route){const edges=[];if(!route?.stages)return edges;for(let i=0;i<route.stages.length;i++){const s=route.stages[i],fallback=routeDestination(route,i);if(s.choices.length){for(const ch of s.choices){const target=routeDestination(route,i,ch);if(target)edges.push({source:s.id,sourceId:ch.id,target,choiceId:ch.id});}}else if(fallback)edges.push({source:s.id,sourceId:s.id,target:fallback,choiceId:''});}return edges;}
export function routeColumns(route){const edges=routeEdges(route),ids=route.stages.map(s=>s.id),depth=new Map(ids.map(id=>[id,0])),indegree=new Map(ids.map(id=>[id,0]));for(const e of edges)if(indegree.has(e.target))indegree.set(e.target,indegree.get(e.target)+1);const queue=ids.filter(id=>!indegree.get(id));let n=0;while(queue.length){const id=queue.shift();n++;for(const e of edges.filter(e=>e.source===id)){if(!depth.has(e.target))continue;depth.set(e.target,Math.max(depth.get(e.target),depth.get(id)+1));indegree.set(e.target,indegree.get(e.target)-1);if(!indegree.get(e.target))queue.push(e.target);}}if(n!==ids.length)return route.stages.map(s=>[s]);const columns=[];for(const s of route.stages){const d=depth.get(s.id);(columns[d]??=[]).push(s);}return columns.filter(Boolean);}
export function selectedRoutePath(route,choices){const seen=new Set(),path=[];let id=route.stages[0]?.id;while(id&&!seen.has(id)){const index=route.stages.findIndex(s=>s.id===id);if(index<0)break;const s=route.stages[index];seen.add(id);path.push(id);let next=routeDestination(route,index);if(s.choices.length){const ch=s.choices.find(ch=>ch.id===choices[s.id]);if(!ch)break;next=routeDestination(route,index,ch);}id=next;}return path;}
export function validateRoute(route,c){if(!routeShape(route))return ['Malformed route, stage, alternative or action schema'];const errors=[],ids=new Set(),allIds=new Set();const add=id=>{if(!/^[-\w]+$/.test(id)||allIds.has(id))errors.push('Missing, invalid or duplicate route ID: '+id);allIds.add(id);};const checkRef=item=>{if(item.entryId){const e=c.entries.find(e=>e.id===item.entryId);if(!e)errors.push('Unknown entry '+item.entryId);else if(item.methodId&&!e.methods.some(m=>m.id===item.methodId))errors.push('Unknown method '+item.methodId);}else if(item.methodId)errors.push('A method requires an entry');for(const id of item.mediaIds)if(!c.videos.some(v=>v.id===id))errors.push('Unknown media '+id);};
 for(const s of route.stages){add(s.id);ids.add(s.id);checkRef(s);if(!s.title.trim())errors.push('Stage title missing '+s.id);if(s.regionId&&!c.regions.some(r=>r.id===s.regionId))errors.push('Unknown region '+s.regionId);if(s.subsectionId&&!c.subsections.some(r=>r.id===s.subsectionId))errors.push('Unknown subsection '+s.subsectionId);for(const ch of s.choices){add(ch.id);if(!ch.title.trim())errors.push('Alternative title missing '+ch.id);if((ch.timing||ch.reliability)&&!ch.basisDate.trim())errors.push('Timing/reliability needs a basis and date '+ch.id);for(const a of ch.actions){add(a.id);checkRef(a);if(!a.title.trim())errors.push('Action title missing '+a.id);}}}
 if(ids.has(ROUTE_END))errors.push('Reserved terminal ID cannot be a stage ID');const edges=routeEdges(route);for(const e of edges)if(!ids.has(e.target))errors.push('Missing next stage '+e.target);const visiting=new Set(),seen=new Set(),order=[];function walk(id){if(visiting.has(id)){errors.push('Unintended cycle at '+id);return;}if(seen.has(id))return;visiting.add(id);seen.add(id);for(const e of edges.filter(e=>e.source===id))if(ids.has(e.target))walk(e.target);visiting.delete(id);order.push(id);}if(route.stages.length)walk(route.stages[0].id);for(const id of ids)if(!seen.has(id))errors.push('Unreachable stage '+id);if(errors.some(e=>e.includes('cycle')||e.includes('duplicate')))return [...new Set(errors)];
 const incoming=new Map();if(route.stages.length)incoming.set(route.stages[0].id,[new Set()]);const canon=s=>JSON.stringify([...s].sort());const check=(requires,state,label)=>{for(const q of requires)if(!state.has(q))errors.push('Unmet declared dependency at '+label+': '+q);};const send=(dest,state)=>{if(!ids.has(dest))return;const a=incoming.get(dest)||[];a.push(state);incoming.set(dest,a);};for(const id of order.reverse()){const s=route.stages.find(s=>s.id===id),states=incoming.get(id)||[new Set()];if(states.some(st=>canon(st)!==canon(states[0])))errors.push('Incompatible reconvergence at '+id+'; align all incoming declared states or use separate next stages');const base=new Set([...states[0]].filter(q=>states.every(st=>st.has(q))));check(s.requires,base,s.id);s.result.forEach(q=>base.add(q));if(!s.choices.length){const edge=edges.find(e=>e.source===id);if(edge)send(edge.target,base);}for(const ch of s.choices){const branch=new Set(base);check(ch.requires,branch,ch.id);for(const a of ch.actions){check(a.requires,branch,a.id);a.result.forEach(q=>branch.add(q));}ch.result.forEach(q=>branch.add(q));const edge=edges.find(e=>e.choiceId===ch.id);if(edge)send(edge.target,branch);}}
 return [...new Set(errors)];}
export function validateCatalog(c,{allowIncomplete=false}={}){const err=[];if(!obj(c)||!obj(c.meta)||c.meta.schemaVersion!==1||!hasStrings(c.meta,['revision','sourceUrl','importedAt'])||!Number.isInteger(c.meta.sourceEntries)||!Number.isInteger(c.meta.sourceVideos)||c.meta.sourceEntries<0||c.meta.sourceEntries>10000||c.meta.sourceVideos<0||c.meta.sourceVideos>10000||!Array.isArray(c.entries)||!c.entries.length||!Array.isArray(c.videos)||!Array.isArray(c.regions)||!Array.isArray(c.subsections)||!Array.isArray(c.routes)||!c.routes.length)return ['Unsupported or malformed catalog schema; at least one entry and guide are required'];
 if(!safeUrl(c.meta.sourceUrl))err.push('Invalid source URL');const unique=(xs,label)=>{const set=new Set();for(const x of xs){if(!obj(x)||!str(x.id)||!/^[-\w]+$/.test(x.id)||set.has(x.id))err.push('Invalid or duplicate '+label+' ID');set.add(x?.id);}return set;};const eids=unique(c.entries,'entry'),vids=unique(c.videos,'media'),rids=unique(c.regions,'region'),sids=unique(c.subsections,'subsection');unique(c.routes,'route');for(let i=1;i<=c.meta.sourceEntries;i++)if(!eids.has('MCD2-'+String(i).padStart(3,'0')))err.push('Missing imported entry MCD2-'+String(i).padStart(3,'0'));for(let i=1;i<=c.meta.sourceVideos;i++)if(!vids.has('VID-'+String(i).padStart(3,'0')))err.push('Missing imported media VID-'+String(i).padStart(3,'0'));if(err.length)return err;const expected=['Squid Coast','Brave Haven','Honeycomb Fields','Howling Woods','Rainy Plains','Frozen Highlands',"Singer's Meadow",'Humbler Huskland','Lullaby Hills','Illager Stronghold'];if(JSON.stringify(c.regions.map(r=>r.name))!==JSON.stringify(expected))err.push('Region labels/order must match the ten requested regions');const date=x=>x===null||x===''||str(x)&&/^\d{4}-\d{2}-\d{2}$/.test(x);const checkReq=(q,label)=>{if(!req(q)){err.push('Malformed prerequisites '+label);return;}for(const id of q.entryIds)if(!eids.has(id))err.push('Unknown prerequisite '+id);};
 for(const e of c.entries){if(!/^MCD2-\d{3,}$/.test(e.id)||!hasStrings(e,['title','summary','type','originalCategory','locationStatus','instructions','notes','discoveryDate','applicability','usefulness','evidenceStatus'])||(!allowIncomplete&&!e.title.trim())||!['tech','skip','strategy','reference'].includes(e.type)||!['general','partially-confirmed','unassigned'].includes(e.locationStatus)||!hasStrings(e.credits,['discovery','refinement','footage','narration'])||!['regionIds','subsectionIds','relatedEntryIds','mediaIds','aliases','warnings'].every(k=>strings(e[k]))||![e.discoveryDate,e.editorialDate,e.retestDate].every(date)||!Array.isArray(e.methods)||!e.methods.length){err.push('Malformed entry '+e.id);continue;}checkReq(e.requirements,e.id);for(const id of e.relatedEntryIds)if(!eids.has(id))err.push('Unknown related technique '+id);for(const id of e.regionIds)if(!rids.has(id))err.push('Unknown region '+id);for(const id of e.subsectionIds)if(!sids.has(id))err.push('Unknown subsection '+id);for(const id of e.mediaIds)if(!vids.has(id))err.push('Unknown media '+id);unique(e.methods,'method');for(const m of e.methods){if(!hasStrings(m,['id','title','instructions','applicability','credits'])||(!allowIncomplete&&!m.title.trim())||!strings(m.mediaIds)){err.push('Malformed method '+m?.id);continue;}for(const id of m.mediaIds)if(!vids.has(id))err.push('Unknown method media '+id);checkReq(m.requirements,m.id);}}
 for(const v of c.videos){if(!/^VID-\d{3,}$/.test(v.id)||!hasStrings(v,['entryId','title','sourceType','url','role','credits'])||!eids.has(v.entryId)||(!safeUrl(v.url)&&!(allowIncomplete&&v.url===''))||(!allowIncomplete&&!v.title.trim())||!['Tutorial','Original proof','Alternative method','Input setup'].includes(v.role))err.push('Invalid media '+v.id);if(v.sourceType==='YouTube'&&!youtube(v.url)&&!(allowIncomplete&&v.url===''))err.push('Invalid YouTube URL '+v.id);if(v.sourceType==='Discord video'&&!(allowIncomplete&&v.url==='')&&!/^https:\/\/discord.com\/channels\/\d+\/\d+\/\d+$/.test(v.url))err.push('Invalid Discord source '+v.id);}
 for(const s of c.subsections){if(!hasStrings(s,['name','status'])||(!allowIncomplete&&!s.name.trim())||s.regionId!==null&&(!str(s.regionId)||!rids.has(s.regionId)))err.push('Invalid subsection '+s.id);if(s.image!==null&&(!hasStrings(s.image,['path','alt','credit'])||!assetPath(s.image.path)||(!allowIncomplete&&!s.image.alt.trim())||![s.image.focalX,s.image.focalY].every(n=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=1)))err.push('Invalid screenshot metadata '+s.id);}
 if(err.length)return [...new Set(err)];for(const r of c.routes){const re=validateRoute(r,c);err.push(...(allowIncomplete?re.filter(e=>/Malformed|invalid|duplicate/.test(e)):re));}return [...new Set(err)];}
/** @param {any} published */
export function restoreDraft(raw,revision,published=null,{allowIncomplete=false}={}){if(!obj(raw)||raw.schemaVersion!==1||!Array.isArray(raw.assets)||!str(raw.baseRevision))throw Error('Unsupported draft version. Preserve this file for manual reconciliation.');if(raw.baseRevision!==revision)throw Error('Revision conflict: this draft was based on '+raw.baseRevision+'; the published catalog is '+revision+'. Reconcile on a GitHub branch/PR. No content was replaced.');const errors=validateCatalog(raw.catalog,{allowIncomplete});if(errors.length)throw Error(errors.join('\n'));const paths=new Set();for(const a of raw.assets){if(!obj(a)||!assetPath(a.path)||paths.has(a.path)||!str(a.data)||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(a.data)||a.data.length>2800000)throw Error('Invalid, duplicate or oversized screenshot asset');paths.add(a.path);}if(published){if(raw.catalog.meta.sourceEntries!==published.meta.sourceEntries||raw.catalog.meta.sourceVideos!==published.meta.sourceVideos||raw.catalog.meta.sourceUrl!==published.meta.sourceUrl)throw Error('Source provenance cannot be replaced by a draft import');const existing=new Set(published.subsections.map(s=>s.image?.path).filter(Boolean));for(const path of paths)if(existing.has(path))throw Error('Screenshot paths are immutable: upload a new asset path instead of replacing '+path);for(const s of raw.catalog.subsections)if(s.image&&!paths.has(s.image.path)&&!existing.has(s.image.path))throw Error('Missing screenshot bytes for '+s.image.path+'; include the asset in the draft or use a known published image');}return raw;}
export async function revisionFor(c){const copy=structuredClone(c);copy.meta.revision='';copy.entries.sort((a,b)=>a.id.localeCompare(b.id));copy.routes.sort((a,b)=>a.id.localeCompare(b.id));function canonical(x){if(Array.isArray(x))return x.map(canonical);if(obj(x))return Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])]));return x;}const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(canonical(copy))));return 'content-'+Array.from(new Uint8Array(digest)).slice(0,8).map(b=>b.toString(16).padStart(2,'0')).join('');}
